adwords:
  client_customer_id: XXX-XXX-XXXX

  developer_token: XXXXXXXXXXXXXXXXXXXXXX
  client_id: XXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXX.XXXXXXXXXXXXXXXXX.XXX
  client_secret: XXXXXXXXXXXXXXXXXXXXXXXX
  refresh_token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
